==> ./quast_A02_Microthrix_Bio17-20151028/metaquast.log <==
/mnt/gaiagpfs/projects/ecosystem_biology/local_tools/quast/metaquast.py -f  -o /scratch/users/snarayanasamy/IMP_MS_data/quast_A02_Microthrix_Bio17-20151028 -R /mnt/nfs/projects/ecosystem_biology/LAO/Genomes/Microthrix/Assemblies/GCF_000299415.1_ASM29941v1_genomic.fna -G /mnt/nfs/projects/ecosystem_biology/LAO/Genomes/Microthrix/Bio17_1/GCF_000299415.1_ASM29941v1_genomic.gff -t 12 -l IMP,IMP-megahit,metAmos,metAmos-IDBA_UD /scratch/users/snarayanasamy/IMP_MS_data/IMP_analysis/A02_20151006-idba/Assembly/MGMT.assembly.merged.fa /scratch/users/snarayanasamy/IMP_MS_data/IMP_analysis/A02_20151007-megahit/Assembly/MGMT.assembly.merged.fa /scratch/users/snarayanasamy/IMP_MS_data/metAmosAnalysis/A02_metAmos/Assemble/out/soapdenovo.31.asm.contig /scratch/users/snarayanasamy/IMP_MS_data/metAmosAnalysis/A02_metAmos-IDBAUD/Assemble/out/idba-ud.31.asm/contig.fa

==> ./quast_A02_Microthrix_RN1-20151028/metaquast.log <==
/mnt/gaiagpfs/projects/ecosystem_biology/local_tools/quast/metaquast.py -f  -o /scratch/users/snarayanasamy/IMP_MS_data/quast_A02_Microthrix_RN1-20151028 -R /mnt/nfs/projects/ecosystem_biology/LAO/Genomes/Microthrix/RN1/RN1.fa -G /mnt/nfs/projects/ecosystem_biology/LAO/Genomes/Microthrix/RN1/GCF_000455525.1_M.parvicella.RN1_genomic.gff -t 12 -l IMP,IMP-megahit,metAmos,metAmos-IDBA_UD /scratch/users/snarayanasamy/IMP_MS_data/IMP_analysis/A02_20151006-idba/Assembly/MGMT.assembly.merged.fa /scratch/users/snarayanasamy/IMP_MS_data/IMP_analysis/A02_20151007-megahit/Assembly/MGMT.assembly.merged.fa /scratch/users/snarayanasamy/IMP_MS_data/metAmosAnalysis/A02_metAmos/Assemble/out/soapdenovo.31.asm.contig /scratch/users/snarayanasamy/IMP_MS_data/metAmosAnalysis/A02_metAmos-IDBAUD/Assemble/out/idba-ud.31.asm/contig.fa

==> ./quast_simDat_20151028/metaquast.log <==
/mnt/gaiagpfs/projects/ecosystem_biology/local_tools/quast/metaquast.py -o /scratch/users/snarayanasamy/IMP_MS_data/quast_simDat_20151028 -t 12 -l IMP,IMP-megahit,metAmos,metAmos-IDBA_UD -R /mnt/nfs/projects/ecosystem_biology/test_datasets/CelajEtAl/73_species/ -f  /scratch/users/snarayanasamy/IMP_MS_data/IMP_analysis/simulated_data_output_20151002-idba/Assembly/MGMT.assembly.merged.fa /scratch/users/snarayanasamy/IMP_MS_data/IMP_analysis/simulated_data_output_20151002-megahit/Assembly/MGMT.assembly.merged.fa /scratch/users/snarayanasamy/IMP_MS_data/metAmosAnalysis/simDat_metAmos/Assemble/out/soapdenovo.31.asm.contig /scratch/users/snarayanasamy/IMP_MS_data/metAmosAnalysis/simDat_metAmos-IDBAUD_corrected/Assemble/out/idba-ud.31.asm/contig.fa

==> ./quast_X310763260-20151028/metaquast.log <==
/mnt/gaiagpfs/projects/ecosystem_biology/local_tools/quast/metaquast.py -o /scratch/users/snarayanasamy/IMP_MS_data/quast_X310763260-20151028 -R /scratch/users/snarayanasamy/IMP_MS_data/quast_X310763260-20151022/quast_downloaded_references/ -f  -t 12 -f  -l IMP,IMP-megahit,metAmos,metAmos-IDBA_UD /scratch/users/snarayanasamy/IMP_MS_data/IMP_analysis/X310763260_20151004-idba/Assembly/MGMT.assembly.merged.fa /scratch/users/snarayanasamy/IMP_MS_data/IMP_analysis/X310763260_20151006-megahit/Assembly/MGMT.assembly.merged.fa /scratch/users/snarayanasamy/IMP_MS_data/metAmosAnalysis/X310763260_metAmos/Assemble/out/proba.asm.contig /scratch/users/snarayanasamy/IMP_MS_data/metAmosAnalysis/X310763260_metAmos-IDBAUD_corrected/Assemble/out/idba-ud.31.asm/contig.fa

==> ./quast_X310763260-20151028_vs_MG_2/metaquast.log <==
/mnt/gaiagpfs/projects/ecosystem_biology/local_tools/quast/metaquast.py -o /scratch/users/snarayanasamy/IMP_MS_data/quast_X310763260-20151028_vs_MG_2 -R /scratch/users/snarayanasamy/IMP_MS_data/quast_X310763260-20151022/quast_downloaded_references/ -f  -t 12 -f  -l IMP,IMP-megahit,metAmos,metAmos-IDBA_UD,metAmos-IDBA_UD-MG /scratch/users/snarayanasamy/IMP_MS_data/IMP_analysis/X310763260_20151004-idba/Assembly/MGMT.assembly.merged.fa /scratch/users/snarayanasamy/IMP_MS_data/IMP_analysis/X310763260_20151006-megahit/Assembly/MGMT.assembly.merged.fa /scratch/users/snarayanasamy/IMP_MS_data/metAmosAnalysis/X310763260_metAmos/Assemble/out/proba.asm.contig /scratch/users/snarayanasamy/IMP_MS_data/metAmosAnalysis/X310763260_metAmos-IDBAUD_corrected/Assemble/out/idba-ud.31.asm/contig.fa /scratch/users/snarayanasamy/IMP_MS_data/metAmosAnalysis/X310763260_metAmos-IDBAUD/Assemble/out/idba-ud.31.asm/contig.fa
