#!/bin/bash -l

source preload_modules.sh

date
## MOCAT
MGR1_MOCAT=$1
MGR2_MOCAT=$2
MGSE_MOCAT=$3
MTR1_MOCAT=$4
MTR2_MOCAT=$5
MTSE_MOCAT=$6

## metAmos
MGR1_METAMOS=$7
MGR2_METAMOS=$8
MTR1_METAMOS=$9
MTR2_METAMOS=${10}

## IMP
MGR1_IMP=${11}
MGR2_IMP=${12}
MGSE_IMP=${13}
MTR1_IMP=${14}
MTR2_IMP=${15}
MTSE_IMP=${16}

SAMPLE=${17}
OUT_DIR=${18}
OUT_LOG=${16}/${15}_IGC.log

MGR1_MOCAT=$MGR1_MOCAT \
MGR2_MOCAT=$MGR2_MOCAT \
MGSE_MOCAT=$MGSE_MOCAT \
MTR1_MOCAT=$MTR1_MOCAT \
MTR2_MOCAT=$MTR2_MOCAT \
MTSE_MOCAT=$MTSE_MOCAT \
MGR1_METAMOS=$MGR1_METAMOS \
MGR2_METAMOS=$MGR2_METAMOS \
MTR1_METAMOS=$MTR1_METAMOS \
MTR2_METAMOS=$MTR2_METAMOS \
MGR1_IMP=$MGR1_IMP \
MGR2_IMP=$MGR2_IMP \
MGSE_IMP=$MGSE_IMP \
MTR1_IMP=$MTR1_IMP \
MTR2_IMP=$MTR2_IMP \
MTSE_IMP=$MTSE_IMP \
SAMPLE=$SAMPLE \
OUT_DIR=$OUT_DIR \
OUT_LOG=$OUT_LOG \
snakemake ALL -np

date
