import os
configfile: "config_mapping.json"

## Parameters required from the config file
MEMCORE = os.environ.get("MEMCORE", config['memory_per_core_gb'])
THREADS = os.environ.get("THREADS", config['threads'])

## Input and output parameters
REFERENCE = os.environ.get("REFERENCE", "/work/projects/ecosystem_biology/MUST/databases/integrated_reference_catalog/IGC.fa")
TMP = os.environ.get("TMP", "/tmp")

## Output directory and logs
OUT_DIR = os.environ.get("OUT_DIR")
OUT_LOG = os.environ.get("OUT_LOG")

## MOCAT
MOCAT_MGR1 = os.environ.get("MOCAT_MGR1")
MOCAT_MGR2 = os.environ.get("MOCAT_MGR2")
MOCAT_MGSE = os.environ.get("MOCAT_MGSE")
MOCAT_MTR1 = os.environ.get("MOCAT_MTR1")
MOCAT_MTR2 = os.environ.get("MOCAT_MTR2")
MOCAT_MTSE = os.environ.get("MOCAT_MTSE")

## MetAmos
METAMOS_MGR1 = os.environ.get("METAMOS_MGR1")
METAMOS_MGR2 = os.environ.get("METAMOS_MGR2")
METAMOS_MTR1 = os.environ.get("METAMOS_MTR1")
METAMOS_MTR2 = os.environ.get("METAMOS_MTR2")

## IMP
MGR1_IMP = os.environ.get("MGR1_IMP")
MGR2_IMP = os.environ.get("MGR2_IMP")
MGSE_IMP = os.environ.get("MGSE_IMP")
MTR1_IMP = os.environ.get("MTR1_IMP")
MTR2_IMP = os.environ.get("MTR2_IMP")
MTSE_IMP = os.environ.get("MTSE_IMP")

SAMPLE = os.environ.get("SAMPLE")

### All rule
rule ALL:
    input:
        "%s/MT_MOCAT_x_HMP.sorted_flagstat.txt" % OUT_DIR,
        "%s/MG_MOCAT_x_HMP.sorted_flagstat.txt" % OUT_DIR,
        "%s/MT_metAmos_x_HMP.sorted_flagstat.txt" % OUT_DIR,
        "%s/MG_metAmos_x_HMP.sorted_flagstat.txt" % OUT_DIR,
        "%s/MT_IMP_x_HMP.sorted_flagstat.txt" % OUT_DIR,
        "%s/MG_IMP_x_HMP.sorted_flagstat.txt" % OUT_DIR
    shell: "echo DONE"

### Index gene catalog using bwa 
rule INDEX_DATABASE:
    input:
        {REFERENCE}
    output:
        expand("{REFERENCE}.amb", REFERENCE=REFERENCE),
        expand("{REFERENCE}.bwt", REFERENCE=REFERENCE),
        expand("{REFERENCE}.pac", REFERENCE=REFERENCE),
        expand("{REFERENCE}.ann", REFERENCE=REFERENCE),
        expand("{REFERENCE}.sa", REFERENCE=REFERENCE)
    benchmark:
        "%s/benchmarks/INDEX_DATABASE.json" % OUT_DIR
    log:
        OUT_LOG
    shell:
        """
        bwa index {input}
        """

include:
    "map_MOCAT.rules"

include:
    "map_metAmos.rules"

include:
    "map_IMP.rules"
